### ISSUE TITLE
Reason Behind needing OpenSSL Source copied into build?

### ISSUE THREAD

**Issue by GoldenBug** [jyao1/openspdm#178]
Hi, 

I was wondering what the reason was for requiring the openssl source be copied into the source tree during compile time, as apposed to using an installed library?

Is there a technical limitation?
Does this library use behavior that is not exposed through the headers?

**Comment by jyao1** [comment]
I don't think there is any technical limitation.

The project started in a non-OS environment, such as UEFI, where we don't have any standard C environment.
We have to add stub function for openssl and build it from source.
We just reused the same way when we enable the emulator later.

Also, we would like to support multiple compilers in different OS environment, such as Visual Studio and GCC with different compiler option. Building from source is an easy option for us.

If you want to link an installed library, you can enable it. But you can only use it from the emulator. It might not work in special environment, such as UEFI.
If you want to contribute back as an option, I am happy to accept it.

**Comment by GoldenBug** [comment]
I was looking at enabling the library for use within an OpenBMC yocto-linux environment but it seems there are quite a few headers in use from openssl that aren't meant to be used in applications.

Are there any future plans to move away from using these internal-only openssl headers / functions?

**Comment by jyao1** [comment]
Sorry, I don't understand your question.

Basically, openssl is just one implementation choice for the crypto for SPDM. 

You may use any other crypto library as you like, such as mbedtls, hardware crypto module, or even your customized openssl.

**Comment by hMcLauchlan** [comment]
Hello!

I work with @GoldenBug , and have also done some digging into the code to figure out how to get rid of the openssl source dependency.

Through some preliminary hacking, I've managed to get the project compiling against `libssl` and `libcrypto` instead of requiring the source. Before I embarked on a PR-quality change, I wanted to run my understanding through y'all, so I don't spend a bunch of time doing something silly that can't be used.

---------- (Below this line is my reading of the code)

### Blockers(To migrating to a "link to existing library" approach):
 
- The project currently links in extra functions on top of the "standard" `openssl` library. It looks like these are remnants / only used for UEFI.
```
$(OUTPUT_DIR)/ossl_store.o : $(SOURCE_DIR)/ossl_store.c
	$(CC) $(CC_FLAGS) -o $@ $(INC) $^

$(OUTPUT_DIR)/rand_pool.o : $(SOURCE_DIR)/rand_pool.c
	$(CC) $(CC_FLAGS) -o $@ $(INC) $^
```
- The project makes use of `openssl` internal headers that are no longer distributed as of `1.1.1g` installs (that is, I can't find them in `/usr/include`). 
     - The use of internal headers (and specifically, access into now opaque structs) makes me think that this code was written for an earlier version of  openssl (Looks like it's https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes).
     - There's core crypto code that relies on having access to these structs. I.e. `Sha3_256*`.
     - Also, other modules outside of `OpensslLib`  use the internal headers.
     
 ### Proposed Changes 
 
- First, to distinguish our use case from the "we don't have the C runtime and so we need to roll everything ourselves" case, add a flag / arg to the root makefiles that distinguishes these cases.
- Then, based on that flag (assuming it's set)
    - We can more or less ignore everything in `OpensslLib`, since the only "extra" there is UEFI only(?).
    - We can remove the necessity for references to internal headers.
        - openssl no longer provides direct access is because they now recommend we call library functions for everything instead of mucking with it ourselves(i.e. use https://www.openssl.org/docs/man1.1.1/man3/EVP_Digest.html instead of messing with the structs directly).  Moving to the new API allows us to remove all of the references to internal headers. Unless there's a good reason for not doing this, we should try to apply this uniformly (not just for this flag).
        - This also involves getting rid of a lot of tests (or maybe rewriting them), which currently verify the behaviour of the core crypto code.  If we migrate to a newer openssl API, then a lot of that core crypto work gets offloaded into openssl, at which point it's not really our responsibility to test the internals anymore.
       - Change makefiles / include headers as necessary (since currently `CrtLibSupport.h` does a lot of lifting for us, but in a system with an accessible libssl/libcrypto, we would also have those headers).
 
### Questions
- Is my understanding correct? In what ways is it incorrect?
- Is there anything special about the version of openssl that master currently generates vs the "normal" one? Is the only difference other than the extra linked-in functions I mentioned above? 
- Is there a technical limitation that necessitates adhering to the pre-openssl-1.1* API that has direct access to structs? If not, are you ok with a sizable refactor/rewrite of the crypto code (and a few other places throughout the repo) to get everything into a `openssl-1.1+` compatible state? 
 

Sorry for the big ol' wall of text, and for any mistakes I made in reasoning through this. I'm pretty new to this area, so I appreciate your patience!

**Comment by jyao1** [comment]
I appreciate your work on that.

I think you are right in most cases.

Yes, please add a flag to indicate this binary build mode. 

There are some terms I don't understand well - e.g. "direct access", so that I cannot comment correct or incorrect.

There is no limitation or necessitates to adhering to pre-openssl-1.1*. It is just where we start from.
Feel free to upgrade, if you want.
For "If we migrate to a newer openssl API, ... point it's not really our responsibility to test the internals anymore." - That is not true. We do need test the usage of openssl wrapper is correct. The test case is still valid and shall be enabled.


In general, please keep below things in mind:
1) Don't break any existing functionality. E.g. the source build shall be supported. All previous designed test shall be supported.
2) If you find a code access an internal header which is not exposed, that is a bug and not the intension. We should fix it.
3) I assume you will enable the binary build in a generic way, which can be used for either openssl or mbedtls.

**Comment by hMcLauchlan** [comment]
Thanks for the quick response!

By direct access I just mean reading/writing struct members directly (vs using a library function).

WRT API / tests, noted.

Based on a cursory look at the mbedtls directory, I think it shouldn't be too much work to do both in one patch. That said, my bandwidth is a bit limited right now, and if it ends up being a bit tricky I might just submit a patch for the openssl side and defer the other. In such a case, the modular nature of the makefiles / code as is means that a future patch for mbedtls will be easy. Please let me know if you have any objections to this.

**Comment by jyao1** [comment]
Sure. You can submit patch to enable openssl first, then mbedtls, or other modules such as cmocka.

My recommendation is: to make binary architecture 1) independent and 2) complete one time, with one example at least.
As such, we can easily copy it for others.

The enabling / implementation can be done step by step.

**Comment by hMcLauchlan** [comment]
Quick question regarding the code: Is there an important reason to support all functions in `BaseCryptLib.h`? On the main page we say "The SPDM lib requires cryptolib API, including random number, symmetric crypto, asymmetric crypto, hash and message authentication code etc.", but inspection of the code reveals that a lot of the functions can be removed.

For example, functions like `Shaxxx_Update` , `Shaxxx_Final` are extraneous when the only directly referenced function from outside this translation unit is `HashAll`. Especially with the changes I'm planning wrt updating the openssl function calls, a lot of those functions can just dissappear. 

Similarly, I've noticed in the mbedtls code that some of those functions are already not referenced by anything that's not test code. For example, `Shaxxx_Update` inside `BaseCryptLibMbedTls` has no callers, since HashAll already skips over it and uses `mbedtls_sha256_ret` directly.

I did some poking around and it seems like the overall structure of `BaseCryptLib.h` follows the structure of intel IPP ([https://software.intel.com/content/www/us/en/develop/documentation/ipp-crypto-reference/top/one-way-hash-primitives/hash-functions.html](url)), which explains the rigid {Init, Update, Duplicate, Final, etc}.

So my question is: is it necessary that we stick to this template? If changing the code obviates the need for these functions (and indeed, the mbedtls code already skips over them), can I prune "unnecessary" functions from `BaseCryptLib.h` ? Or is there a very good reason that we must adhere to this?

Something else that confuses me is the structure of some tests (such as `ValidateCryptDigest`), in which we verify Sha{Init, Update, Final} produces correct output AND HashAll produces correct output. We do this despite only ever calling HashAll in non-test code. I think you may have alluded to this in a prior post, but I'm a bit confused by what this is trying to accomplish.

Would love to hear your thoughts on this; thanks!

**Comment by jyao1** [comment]
Good question. Let me answer one by one.

1) In general, the history of the APIs, why there are unused APIs.

I derive them from EDKII CryptoPkg, same as the test case.
I did some cleanup but it might not be complete.

So if we think some APIs will never be used in openspdm, yes, we can remove them in lib and remove them in test. No doubt.
If you want to change APIs for openssl 3.0, that is also OK. Please them make it implementable for a) openssl 1.1 (EDKII still use it), b) mbedtls, c) make all tests pass.


2) Specifically, the SHAxxx_start/update/finish.

There is debate if we want to use 3 steps APIs HASH_start/update/finish, or 1 step HASH_all. There are PROs and CONs.
I choose to use HASH_ALL, just make the initial code simple.

Now, I hear more and more voice that we should consider 3 steps HASH_start/update/finish, because we don't want to save large portion of message data in the SPDM context, esp for small devices. Of course, the overhead will be SHA_Context data - but some devices have hardware engine.
It is in the plan that we will replace HSAH_ALL with HASH_START/UPDATE/FINISH later.

I recommend we still keep them in library .h, and keep the test code.

**Comment by jyao1** [comment]
migrate binary build support to https://github.com/DMTF/libspdm/issues/25

**Comment by jyao1** [comment]
@hMcLauchlan, We move the patch to https://github.com/DMTF/libspdm. Would you please take a look, if that still works?

If no, please file an issue or submit pull request at https://github.com/DMTF/libspdm/issues.
